<?php
$z[0]=Array("channelartlist","\r\n        <li class=\"li1 {dede:field.currentstyle/}\"> <a class=\"a1\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n          <ul class=\"ul1\">\r\n            {dede:channel type='son' noself='true'}\r\n            <li class=\"li3 \"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",295,747);
$z[0][4]['typeid']="top";
$z[0][4]['currentstyle']="active";

?>